zscores <- read.csv("./zscores.csv")
library(ggplot2)
g <- ggplot(zscores, aes(relativeDistance, avgZScore))
g <- g + facet_grid(.~Continent)
g + geom_point()
g <- ggplot(zscores, aes(relativeDistance, avgZScore))
g <- g + facet_grid(Continent~.)
g + geom_point()
g <- ggplot(zscores, aes(relativeDistance, avgZScore))
g <- g + facet_grid(.~Continent)
g + geom_point()
g <- ggplot(zscores, aes(relativeDistance, avgZScore))
g <- g + facet_grid(.~Continent)
g + geom_boxplot()
g <- ggplot(zscores, aes(avgZScore))
g <- g + facet_grid(.~Continent)
g + geom_boxplot()
g <- ggplot(zscores, aes(Continent, avgZScore))
g + geom_boxplot()
zscores$Continent <- as.factor(zscores$Continent)
g <- ggplot(zscores, aes(Continent, avgZScore))
g + geom_boxplot()
g + geom_boxplot() + ylim(-0.25, 0)
